import { Report, ReportType } from '../backend';
import { formatDate, formatCurrency } from '../lib/format';

export async function downloadReportPdf(report: Report, results: any) {
  const reportTypeName = getReportTypeName(report.reportType);
  const dateRange = `${formatDate(Number(report.startDate))} - ${formatDate(Number(report.endDate))}`;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Failed to open print window');
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${report.name}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
          }
          h1 {
            font-size: 24px;
            margin-bottom: 8px;
          }
          .subtitle {
            color: #666;
            margin-bottom: 24px;
          }
          .section {
            margin-bottom: 24px;
          }
          .section-title {
            font-size: 18px;
            font-weight: 600;
            margin-bottom: 12px;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 8px;
          }
          .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 16px;
            margin-bottom: 24px;
          }
          .info-item {
            padding: 12px;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
          }
          .info-label {
            font-size: 12px;
            color: #666;
            margin-bottom: 4px;
          }
          .info-value {
            font-weight: 600;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
          }
          th, td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #e5e7eb;
          }
          th {
            font-weight: 600;
            background-color: #f9fafb;
          }
          .text-right {
            text-align: right;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #666;
            font-size: 12px;
          }
          @media print {
            body {
              padding: 20px;
            }
          }
        </style>
      </head>
      <body>
        <h1>${report.name}</h1>
        <div class="subtitle">${reportTypeName}</div>

        <div class="section">
          <div class="section-title">Report Summary</div>
          <div class="info-grid">
            <div class="info-item">
              <div class="info-label">Report Type</div>
              <div class="info-value">${reportTypeName}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Date Range</div>
              <div class="info-value">${dateRange}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Created</div>
              <div class="info-value">${formatDate(Number(report.createdAt))}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Generated</div>
              <div class="info-value">${formatDate(Date.now())}</div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Report Data</div>
          <p style="color: #666;">Detailed results will be displayed here when viewing the full report.</p>
        </div>

        <div class="footer">
          Generated by Firefly Lite - ${formatDate(Date.now())}
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();

  setTimeout(() => {
    printWindow.print();
  }, 250);
}

function getReportTypeName(type: ReportType): string {
  switch (type) {
    case ReportType.incomeVsExpenses:
      return 'Income vs. Expenses';
    case ReportType.categoryBreakdown:
      return 'Category Breakdown';
    default:
      return 'Unknown Report Type';
  }
}
