/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : AccountId,
  'balance' : number,
  'name' : string,
}
export type AccountId = bigint;
export interface Budget {
  'id' : BudgetId,
  'month' : bigint,
  'carryOver' : number,
  'categoryLimits' : Array<BudgetCategoryLimit>,
}
export interface BudgetCategoryLimit {
  'categoryId' : CategoryId,
  'limitAmount' : number,
}
export type BudgetId = bigint;
export interface BudgetSummary {
  'month' : bigint,
  'totalIncomeBudget' : number,
  'actualIncome' : number,
  'actualExpenses' : number,
  'remainingIncomeBudget' : number,
  'totalExpenseBudget' : number,
  'remainingExpenseBudget' : number,
}
export interface Category {
  'id' : CategoryId,
  'isExpense' : boolean,
  'name' : string,
}
export type CategoryId = bigint;
export interface Transaction {
  'id' : TransactionId,
  'categoryId' : CategoryId,
  'accountId' : AccountId,
  'date' : bigint,
  'amount' : number,
}
export type TransactionId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<[string], AccountId>,
  'createBudget' : ActorMethod<
    [bigint, Array<BudgetCategoryLimit>, number],
    BudgetId
  >,
  'createCategory' : ActorMethod<[string, boolean], CategoryId>,
  'createTransaction' : ActorMethod<
    [AccountId, CategoryId, number, bigint],
    TransactionId
  >,
  'deleteBudget' : ActorMethod<[BudgetId], undefined>,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getBudget' : ActorMethod<[BudgetId], [] | [Budget]>,
  'getBudgetSummary' : ActorMethod<[bigint], BudgetSummary>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<Transaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudget' : ActorMethod<
    [BudgetId, bigint, Array<BudgetCategoryLimit>, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];