/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountId = IDL.Nat;
export const BankConnectionId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const BudgetCategoryLimit = IDL.Record({
  'categoryId' : CategoryId,
  'limitAmount' : IDL.Float64,
});
export const BudgetId = IDL.Nat;
export const ReportType = IDL.Variant({
  'categoryBreakdown' : IDL.Null,
  'incomeVsExpenses' : IDL.Null,
});
export const TagId = IDL.Nat;
export const TransactionId = IDL.Nat;
export const CsvTransactionRow = IDL.Record({
  'categoryId' : CategoryId,
  'accountId' : AccountId,
  'date' : IDL.Int,
  'tagIds' : IDL.Vec(TagId),
  'amount' : IDL.Float64,
});
export const Account = IDL.Record({
  'id' : AccountId,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
});
export const BankConnectionStatus = IDL.Variant({
  'syncError' : IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int }),
  'idle' : IDL.Null,
  'lastSynced' : IDL.Record({ 'timestamp' : IDL.Int }),
  'inProgress' : IDL.Null,
});
export const BankConnection = IDL.Record({
  'id' : BankConnectionId,
  'status' : BankConnectionStatus,
  'name' : IDL.Text,
  'connectionType' : IDL.Text,
  'nextSyncTimestamp' : IDL.Opt(IDL.Int),
  'createdTimestamp' : IDL.Int,
  'lastSync' : IDL.Opt(IDL.Int),
  'retryAttempts' : IDL.Nat,
});
export const Budget = IDL.Record({
  'id' : BudgetId,
  'month' : IDL.Int,
  'carryOver' : IDL.Float64,
  'categoryLimits' : IDL.Vec(BudgetCategoryLimit),
});
export const BudgetSummary = IDL.Record({
  'month' : IDL.Int,
  'totalIncomeBudget' : IDL.Float64,
  'actualIncome' : IDL.Float64,
  'actualExpenses' : IDL.Float64,
  'remainingIncomeBudget' : IDL.Float64,
  'totalExpenseBudget' : IDL.Float64,
  'remainingExpenseBudget' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : CategoryId,
  'isExpense' : IDL.Bool,
  'name' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'filters' : IDL.Opt(IDL.Text),
  'endDate' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'reportType' : ReportType,
  'updatedAt' : IDL.Int,
  'startDate' : IDL.Int,
});
export const Tag = IDL.Record({ 'id' : TagId, 'name' : IDL.Text });
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'categoryId' : CategoryId,
  'accountId' : AccountId,
  'date' : IDL.Int,
  'tags' : IDL.Vec(TagId),
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func([IDL.Text], [AccountId], []),
  'createBankConnection' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BankConnectionId],
      [],
    ),
  'createBudget' : IDL.Func(
      [IDL.Int, IDL.Vec(BudgetCategoryLimit), IDL.Float64],
      [BudgetId],
      [],
    ),
  'createCategory' : IDL.Func([IDL.Text, IDL.Bool], [CategoryId], []),
  'createReport' : IDL.Func(
      [ReportType, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createTag' : IDL.Func([IDL.Text], [TagId], []),
  'createTransaction' : IDL.Func(
      [AccountId, CategoryId, IDL.Float64, IDL.Int, IDL.Vec(TagId)],
      [TransactionId],
      [],
    ),
  'createTransactionsFromCsvRows' : IDL.Func(
      [IDL.Vec(CsvTransactionRow)],
      [IDL.Vec(TransactionId)],
      [],
    ),
  'deleteBankConnection' : IDL.Func([BankConnectionId], [], []),
  'deleteBudget' : IDL.Func([BudgetId], [], []),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'deleteTag' : IDL.Func([TagId], [], []),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getBankConnection' : IDL.Func(
      [BankConnectionId],
      [IDL.Opt(BankConnection)],
      ['query'],
    ),
  'getBankConnections' : IDL.Func([], [IDL.Vec(BankConnection)], ['query']),
  'getBudget' : IDL.Func([BudgetId], [IDL.Opt(Budget)], ['query']),
  'getBudgetSummary' : IDL.Func([IDL.Int], [BudgetSummary], ['query']),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncBankConnection' : IDL.Func([BankConnectionId], [], []),
  'updateBankConnectionSyncStatus' : IDL.Func(
      [BankConnectionId, BankConnectionStatus],
      [],
      [],
    ),
  'updateBudget' : IDL.Func(
      [BudgetId, IDL.Int, IDL.Vec(BudgetCategoryLimit), IDL.Float64],
      [],
      [],
    ),
  'updateReport' : IDL.Func(
      [IDL.Nat, ReportType, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountId = IDL.Nat;
  const BankConnectionId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const BudgetCategoryLimit = IDL.Record({
    'categoryId' : CategoryId,
    'limitAmount' : IDL.Float64,
  });
  const BudgetId = IDL.Nat;
  const ReportType = IDL.Variant({
    'categoryBreakdown' : IDL.Null,
    'incomeVsExpenses' : IDL.Null,
  });
  const TagId = IDL.Nat;
  const TransactionId = IDL.Nat;
  const CsvTransactionRow = IDL.Record({
    'categoryId' : CategoryId,
    'accountId' : AccountId,
    'date' : IDL.Int,
    'tagIds' : IDL.Vec(TagId),
    'amount' : IDL.Float64,
  });
  const Account = IDL.Record({
    'id' : AccountId,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
  });
  const BankConnectionStatus = IDL.Variant({
    'syncError' : IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int }),
    'idle' : IDL.Null,
    'lastSynced' : IDL.Record({ 'timestamp' : IDL.Int }),
    'inProgress' : IDL.Null,
  });
  const BankConnection = IDL.Record({
    'id' : BankConnectionId,
    'status' : BankConnectionStatus,
    'name' : IDL.Text,
    'connectionType' : IDL.Text,
    'nextSyncTimestamp' : IDL.Opt(IDL.Int),
    'createdTimestamp' : IDL.Int,
    'lastSync' : IDL.Opt(IDL.Int),
    'retryAttempts' : IDL.Nat,
  });
  const Budget = IDL.Record({
    'id' : BudgetId,
    'month' : IDL.Int,
    'carryOver' : IDL.Float64,
    'categoryLimits' : IDL.Vec(BudgetCategoryLimit),
  });
  const BudgetSummary = IDL.Record({
    'month' : IDL.Int,
    'totalIncomeBudget' : IDL.Float64,
    'actualIncome' : IDL.Float64,
    'actualExpenses' : IDL.Float64,
    'remainingIncomeBudget' : IDL.Float64,
    'totalExpenseBudget' : IDL.Float64,
    'remainingExpenseBudget' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : CategoryId,
    'isExpense' : IDL.Bool,
    'name' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'filters' : IDL.Opt(IDL.Text),
    'endDate' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'reportType' : ReportType,
    'updatedAt' : IDL.Int,
    'startDate' : IDL.Int,
  });
  const Tag = IDL.Record({ 'id' : TagId, 'name' : IDL.Text });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'categoryId' : CategoryId,
    'accountId' : AccountId,
    'date' : IDL.Int,
    'tags' : IDL.Vec(TagId),
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func([IDL.Text], [AccountId], []),
    'createBankConnection' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BankConnectionId],
        [],
      ),
    'createBudget' : IDL.Func(
        [IDL.Int, IDL.Vec(BudgetCategoryLimit), IDL.Float64],
        [BudgetId],
        [],
      ),
    'createCategory' : IDL.Func([IDL.Text, IDL.Bool], [CategoryId], []),
    'createReport' : IDL.Func(
        [ReportType, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createTag' : IDL.Func([IDL.Text], [TagId], []),
    'createTransaction' : IDL.Func(
        [AccountId, CategoryId, IDL.Float64, IDL.Int, IDL.Vec(TagId)],
        [TransactionId],
        [],
      ),
    'createTransactionsFromCsvRows' : IDL.Func(
        [IDL.Vec(CsvTransactionRow)],
        [IDL.Vec(TransactionId)],
        [],
      ),
    'deleteBankConnection' : IDL.Func([BankConnectionId], [], []),
    'deleteBudget' : IDL.Func([BudgetId], [], []),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'deleteTag' : IDL.Func([TagId], [], []),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getBankConnection' : IDL.Func(
        [BankConnectionId],
        [IDL.Opt(BankConnection)],
        ['query'],
      ),
    'getBankConnections' : IDL.Func([], [IDL.Vec(BankConnection)], ['query']),
    'getBudget' : IDL.Func([BudgetId], [IDL.Opt(Budget)], ['query']),
    'getBudgetSummary' : IDL.Func([IDL.Int], [BudgetSummary], ['query']),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncBankConnection' : IDL.Func([BankConnectionId], [], []),
    'updateBankConnectionSyncStatus' : IDL.Func(
        [BankConnectionId, BankConnectionStatus],
        [],
        [],
      ),
    'updateBudget' : IDL.Func(
        [BudgetId, IDL.Int, IDL.Vec(BudgetCategoryLimit), IDL.Float64],
        [],
        [],
      ),
    'updateReport' : IDL.Func(
        [IDL.Nat, ReportType, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };